# Generated by Django 5.1.7 on 2026-07-12 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0003_phase5_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System')], default='text', max_length=10, verbose_name='message type')),
                ('content', models.TextField(max_length=5000, verbose_name='content')),
                ('is_system_message', models.BooleanField(default=False, verbose_name='is system message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sent at')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.consultation', verbose_name='consultation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'consultation message',
                'verbose_name_plural': 'consultation messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorInternalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=5000, verbose_name='content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='consultations.consultation', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'doctor internal note',
                'verbose_name_plural': 'doctor internal notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='read at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='messaging.consultationmessage', verbose_name='message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_receipts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message read receipt',
                'verbose_name_plural': 'message read receipts',
            },
        ),
        migrations.AddIndex(
            model_name='consultationmessage',
            index=models.Index(fields=['consultation', 'sent_at'], name='messaging_c_consult_43db1a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationmessage',
            index=models.Index(fields=['sender', 'sent_at'], name='messaging_c_sender__7f298d_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationmessage',
            index=models.Index(fields=['message_type'], name='messaging_c_message_65093d_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorinternalnote',
            index=models.Index(fields=['consultation'], name='messaging_d_consult_149097_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorinternalnote',
            index=models.Index(fields=['author'], name='messaging_d_author__6346f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadreceipt',
            unique_together={('message', 'user')},
        ),
    ]
