# Generated by Django 5.1.15 on 2026-08-01 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultation_completed_at_doctorconsultationaction'),
        ('messaging', '0002_message_client_request_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinternalnote',
            name='client_request_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='client request ID'),
        ),
        migrations.AddConstraint(
            model_name='doctorinternalnote',
            constraint=models.UniqueConstraint(fields=('author', 'client_request_id'), name='internal_note_unique_author_request_id'),
        ),
    ]
