# Generated by Django 5.1.7 on 2026-07-12 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_intake', '0001_initial'),
        ('consultations', '0002_alter_consultation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=15, verbose_name='status')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='chief complaint')),
                ('history_of_present_illness', models.TextField(blank=True, verbose_name='history of present illness')),
                ('symptoms', models.JSONField(blank=True, default=list, verbose_name='symptoms')),
                ('severity', models.IntegerField(blank=True, null=True, verbose_name='severity')),
                ('onset_date', models.DateField(blank=True, null=True, verbose_name='onset date')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='duration')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('triggers', models.TextField(blank=True, verbose_name='triggers')),
                ('relieving_factors', models.TextField(blank=True, verbose_name='relieving factors')),
                ('past_medical_history', models.TextField(blank=True, verbose_name='past medical history')),
                ('medications', models.JSONField(blank=True, default=list, verbose_name='medications')),
                ('allergies', models.JSONField(blank=True, default=list, verbose_name='allergies')),
                ('family_history', models.TextField(blank=True, verbose_name='family history')),
                ('social_history', models.TextField(blank=True, verbose_name='social history')),
                ('review_of_systems', models.TextField(blank=True, verbose_name='review of systems')),
                ('additional_notes', models.TextField(blank=True, verbose_name='additional notes')),
                ('doctor_notes', models.TextField(blank=True, verbose_name='doctor notes')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='finalized at')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='consultations.consultation', verbose_name='consultation')),
                ('intake_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='ai_intake.aiintakesession', verbose_name='intake session')),
            ],
            options={
                'verbose_name': 'medical record draft',
                'verbose_name_plural': 'medical record drafts',
            },
        ),
    ]
