# Generated by Django 5.1.15 on 2026-08-01 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='assessment',
            field=models.TextField(blank=True, verbose_name='assessment'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='clinical_outcome',
            field=models.CharField(blank=True, choices=[('remote_care_completed', 'Remote care completed'), ('follow_up_required', 'Follow-up required'), ('physical_visit_required', 'Physical visit required'), ('transferred', 'Transferred'), ('emergency_escalated', 'Emergency escalated')], max_length=32, verbose_name='clinical outcome'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='clinical_summary',
            field=models.TextField(blank=True, verbose_name='clinical summary'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='differential_considerations',
            field=models.TextField(blank=True, verbose_name='differential considerations'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_medical_records', to=settings.AUTH_USER_MODEL, verbose_name='finalized by'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='follow_up_plan',
            field=models.TextField(blank=True, verbose_name='follow-up plan'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='outcome_recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='outcome recorded at'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='patient_instructions',
            field=models.TextField(blank=True, verbose_name='patient instructions'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='physical_visit_reason',
            field=models.TextField(blank=True, verbose_name='physical visit reason'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='provenance',
            field=models.JSONField(blank=True, default=dict, verbose_name='provenance'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='recommendations'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='treatment_plan',
            field=models.TextField(blank=True, verbose_name='treatment plan'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='version'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='warning_signs',
            field=models.TextField(blank=True, verbose_name='warning signs'),
        ),
        migrations.AddField(
            model_name='medicalrecorddraft',
            name='working_diagnosis',
            field=models.TextField(blank=True, verbose_name='working diagnosis'),
        ),
        migrations.CreateModel(
            name='MedicalRecordAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=24)),
                ('client_request_id', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('result_version', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record_actions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='medical_records.medicalrecorddraft')),
            ],
            options={
                'indexes': [models.Index(fields=['record', '-created_at'], name='medical_rec_record__b55dbd_idx'), models.Index(fields=['actor', 'client_request_id'], name='medical_rec_actor_i_758899_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor', 'client_request_id'), name='medical_record_unique_actor_request')],
            },
        ),
    ]
