# Generated by Django 5.1.7 on 2026-07-13 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0004_consultationprioritychange_consultationtransfer'),
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_provider', models.CharField(help_text="Name of the storage backend (e.g. 'local', 'railway_bucket').", max_length=50, verbose_name='storage provider')),
                ('storage_key', models.CharField(help_text='Opaque key generated by the server. Never exposed to clients.', max_length=500, unique=True, verbose_name='storage key')),
                ('original_filename', models.CharField(help_text='Original filename from upload (metadata only).', max_length=500, verbose_name='original filename')),
                ('safe_display_name', models.CharField(blank=True, help_text='Sanitized filename safe for display and Content-Disposition.', max_length=500, verbose_name='safe display name')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='extension')),
                ('declared_mime_type', models.CharField(blank=True, max_length=100, verbose_name='declared MIME type')),
                ('detected_mime_type', models.CharField(blank=True, max_length=100, verbose_name='detected MIME type')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='size bytes')),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256')),
                ('category', models.CharField(choices=[('medical_report', 'Medical Report'), ('laboratory_result', 'Laboratory Result'), ('medical_image', 'Medical Image'), ('referral', 'Referral'), ('identity_document', 'Identity Document'), ('consent_document', 'Consent Document'), ('other', 'Other')], default='other', max_length=30, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('quarantined', 'Quarantined'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('scan_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('clean', 'Clean'), ('suspicious', 'Suspicious'), ('infected', 'Infected'), ('failed', 'Failed')], db_index=True, default='not_required', max_length=20, verbose_name='scan status')),
                ('scan_provider', models.CharField(blank=True, max_length=50, verbose_name='scan provider')),
                ('scan_reference', models.CharField(blank=True, max_length=255, verbose_name='scan reference')),
                ('scan_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='scan completed at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='deletion reason')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consultations.consultation', verbose_name='consultation')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_attachments', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'consultation attachment',
                'verbose_name_plural': 'consultation attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('scan_started', 'Scan Started'), ('scan_completed', 'Scan Completed'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('deleted', 'Deleted'), ('restored', 'Restored'), ('rejected', 'Rejected'), ('storage_error', 'Storage Error')], max_length=30, verbose_name='event type')),
                ('safe_metadata', models.JSONField(blank=True, default=dict, help_text='Non-medical metadata: size, category, status transition.', verbose_name='safe metadata')),
                ('request_ip_hash', models.CharField(blank=True, max_length=64, verbose_name='request IP hash')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='attachments.consultationattachment', verbose_name='attachment')),
            ],
            options={
                'verbose_name': 'attachment audit event',
                'verbose_name_plural': 'attachment audit events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record_links', to='attachments.consultationattachment', verbose_name='attachment')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medical_records.medicalrecorddraft', verbose_name='medical record')),
            ],
            options={
                'verbose_name': 'medical record attachment',
                'verbose_name_plural': 'medical record attachments',
            },
        ),
        migrations.AddIndex(
            model_name='consultationattachment',
            index=models.Index(fields=['consultation', 'created_at'], name='attachments_consult_eeb8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationattachment',
            index=models.Index(fields=['uploaded_by'], name='attachments_uploade_d3c65e_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationattachment',
            index=models.Index(fields=['status'], name='attachments_status_89bba1_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationattachment',
            index=models.Index(fields=['scan_status'], name='attachments_scan_st_30412b_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationattachment',
            index=models.Index(fields=['sha256'], name='attachments_sha256_c21561_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationattachment',
            index=models.Index(fields=['is_deleted'], name='attachments_is_dele_b300dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicalrecordattachment',
            unique_together={('medical_record', 'attachment')},
        ),
    ]
