# Generated by Django 5.1.7 on 2026-07-26 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('account', 'Account'), ('privacy', 'Privacy'), ('doctor', 'Doctor'), ('consultation', 'Consultation'), ('security', 'Security'), ('system', 'System')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('failed', 'Failed')], default='success', max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=20, null=True)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=255)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('retention_class', models.CharField(choices=[('security_critical', 'Security Critical'), ('privacy_decision', 'Privacy Decision'), ('operational', 'Operational'), ('informational', 'Informational')], default='operational', max_length=30)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='core_audite_event_t_9151ef_idx'), models.Index(fields=['category', 'severity'], name='core_audite_categor_a8f07c_idx'), models.Index(fields=['actor_id', 'occurred_at'], name='core_audite_actor_i_43737a_idx')],
            },
        ),
    ]
