from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.attachments.choices import (
    AttachmentCategory,
    AttachmentEventType,
    AttachmentStatus,
    ScanStatus,
)
from apps.core.models import BaseModel

User = get_user_model()


class ConsultationAttachment(BaseModel):
    """A file attached to a consultation."""

    consultation = models.ForeignKey(
        "consultations.Consultation",
        on_delete=models.CASCADE,
        related_name="attachments",
        verbose_name=_("consultation"),
    )
    uploaded_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="uploaded_attachments",
        verbose_name=_("uploaded by"),
    )
    storage_provider = models.CharField(
        _("storage provider"), max_length=50,
        help_text=_("Name of the storage backend (e.g. 'local', 'railway_bucket')."),
    )
    storage_key = models.CharField(
        _("storage key"), max_length=500, unique=True,
        help_text=_("Opaque key generated by the server. Never exposed to clients."),
    )
    original_filename = models.CharField(
        _("original filename"), max_length=500,
        help_text=_("Original filename from upload (metadata only)."),
    )
    safe_display_name = models.CharField(
        _("safe display name"), max_length=500, blank=True,
        help_text=_("Sanitized filename safe for display and Content-Disposition."),
    )
    extension = models.CharField(
        _("extension"), max_length=20, blank=True,
    )
    declared_mime_type = models.CharField(
        _("declared MIME type"), max_length=100, blank=True,
    )
    detected_mime_type = models.CharField(
        _("detected MIME type"), max_length=100, blank=True,
    )
    size_bytes = models.BigIntegerField(
        _("size bytes"), default=0,
    )
    sha256 = models.CharField(
        _("SHA-256"), max_length=64, blank=True, db_index=True,
    )
    category = models.CharField(
        _("category"),
        max_length=30,
        choices=AttachmentCategory.choices,
        default=AttachmentCategory.OTHER,
    )
    description = models.TextField(_("description"), blank=True)
    status = models.CharField(
        _("status"),
        max_length=20,
        choices=AttachmentStatus.choices,
        default=AttachmentStatus.PENDING,
        db_index=True,
    )
    scan_status = models.CharField(
        _("scan status"),
        max_length=20,
        choices=ScanStatus.choices,
        default=ScanStatus.NOT_REQUIRED,
        db_index=True,
    )
    scan_provider = models.CharField(
        _("scan provider"), max_length=50, blank=True,
    )
    scan_reference = models.CharField(
        _("scan reference"), max_length=255, blank=True,
    )
    scan_completed_at = models.DateTimeField(
        _("scan completed at"), null=True, blank=True,
    )
    quarantine_reason = models.CharField(
        _("quarantine reason"), max_length=255, blank=True,
    )
    rejection_reason = models.CharField(
        _("rejection reason"), max_length=500, blank=True,
    )
    storage_deleted_at = models.DateTimeField(
        _("storage deleted at"), null=True, blank=True,
        help_text=_("When retention processing removed underlying file bytes."),
    )
    is_deleted = models.BooleanField(
        _("is deleted"), default=False, db_index=True,
    )
    deleted_at = models.DateTimeField(
        _("deleted at"), null=True, blank=True,
    )
    deleted_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="deleted_attachments",
        verbose_name=_("deleted by"),
    )
    deletion_reason = models.TextField(_("deletion reason"), blank=True)

    class Meta:
        verbose_name = _("consultation attachment")
        verbose_name_plural = _("consultation attachments")
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["consultation", "created_at"]),
            models.Index(fields=["uploaded_by"]),
            models.Index(fields=["status"]),
            models.Index(fields=["scan_status"]),
            models.Index(fields=["sha256"]),
            models.Index(fields=["is_deleted"]),
        ]

    def __str__(self) -> str:
        return f"Attachment {self.id} — {self.original_filename}"

    @property
    def is_available(self) -> bool:
        return self.status == AttachmentStatus.AVAILABLE and not self.is_deleted


class AttachmentAuditEvent(BaseModel):
    """Immutable audit trail for attachment operations."""

    attachment = models.ForeignKey(
        ConsultationAttachment,
        on_delete=models.CASCADE,
        related_name="audit_events",
        verbose_name=_("attachment"),
    )
    actor = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_("actor"),
    )
    event_type = models.CharField(
        _("event type"),
        max_length=30,
        choices=AttachmentEventType.choices,
    )
    safe_metadata = models.JSONField(
        _("safe metadata"), default=dict, blank=True,
        help_text=_("Non-medical metadata: size, category, status transition."),
    )
    request_ip_hash = models.CharField(
        _("request IP hash"), max_length=64, blank=True,
    )

    class Meta:
        verbose_name = _("attachment audit event")
        verbose_name_plural = _("attachment audit events")
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"Audit {self.event_type} — {self.attachment_id} by {self.actor_id}"


class MedicalRecordAttachment(BaseModel):
    """Links a medical record to an attachment without duplicating the file."""

    medical_record = models.ForeignKey(
        "medical_records.MedicalRecordDraft",
        on_delete=models.CASCADE,
        related_name="attachments",
        verbose_name=_("medical record"),
    )
    attachment = models.ForeignKey(
        ConsultationAttachment,
        on_delete=models.PROTECT,
        related_name="medical_record_links",
        verbose_name=_("attachment"),
    )
    added_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_("added by"),
    )
    notes = models.TextField(_("notes"), blank=True)

    class Meta:
        verbose_name = _("medical record attachment")
        verbose_name_plural = _("medical record attachments")
        unique_together = [("medical_record", "attachment")]

    def __str__(self) -> str:
        return f"Record {self.medical_record_id} ↔ Attachment {self.attachment_id}"
