# Generated by Django 5.1.7 on 2026-07-12 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_doctoravailability'),
        ('patients', '0001_initial'),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('intake_in_progress', 'Intake in Progress'), ('awaiting_patient_response', 'Awaiting Patient Response'), ('awaiting_doctor_response', 'Awaiting Doctor Response'), ('under_review', 'Under Review'), ('follow_up_required', 'Follow-up Required'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=30, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='priority')),
                ('description', models.TextField(blank=True, help_text='Initial description of the consultation request.', verbose_name='description')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation (required when cancelling).', verbose_name='cancellation reason')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='doctors.doctorprofile', verbose_name='doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patientprofile', verbose_name='patient')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='specialties.specialty', verbose_name='specialty')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='consultatio_status_787364_idx'), models.Index(fields=['patient', 'status'], name='consultatio_patient_a614a6_idx'), models.Index(fields=['doctor', 'status'], name='consultatio_doctor__41a060_idx'), models.Index(fields=['specialty', 'status'], name='consultatio_special_9ca31a_idx')],
            },
        ),
    ]
