# Generated by Django 5.1.7 on 2026-07-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('intake_in_progress', 'Intake in Progress'), ('intake_completed', 'Intake Completed'), ('doctor_review', 'Doctor Review'), ('awaiting_patient_response', 'Awaiting Patient Response'), ('awaiting_doctor_response', 'Awaiting Doctor Response'), ('under_review', 'Under Review'), ('follow_up_required', 'Follow-up Required'), ('physical_visit_required', 'Physical Visit Required'), ('transferred', 'Transferred'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('emergency_escalated', 'Emergency Escalated')], default='submitted', max_length=30, verbose_name='status'),
        ),
    ]
