# Generated by Django 5.1.7 on 2026-07-12 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_phase5_models'),
        ('doctors', '0002_doctoravailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationPriorityChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_priority', models.CharField(max_length=10, verbose_name='previous priority')),
                ('new_priority', models.CharField(max_length=10, verbose_name='new priority')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the priority change.', max_length=500, verbose_name='reason')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_changes', to='consultations.consultation', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'consultation priority change',
                'verbose_name_plural': 'consultation priority changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(help_text='Reason for the transfer.', max_length=1000, verbose_name='reason')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='consultations.consultation', verbose_name='consultation')),
                ('new_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='doctors.doctorprofile', verbose_name='new doctor')),
                ('previous_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='doctors.doctorprofile', verbose_name='previous doctor')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL, verbose_name='transferred by')),
            ],
            options={
                'verbose_name': 'consultation transfer',
                'verbose_name_plural': 'consultation transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
