# Generated by Django 5.1.15 on 2026-08-01 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_client_request_id'),
        ('doctors', '0005_add_licensedocument_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
        migrations.CreateModel(
            name='DoctorConsultationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=40)),
                ('old_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('intake_in_progress', 'Intake in Progress'), ('intake_completed', 'Intake Completed'), ('doctor_review', 'Doctor Review'), ('awaiting_patient_response', 'Awaiting Patient Response'), ('awaiting_doctor_response', 'Awaiting Doctor Response'), ('under_review', 'Under Review'), ('follow_up_required', 'Follow-up Required'), ('physical_visit_required', 'Physical Visit Required'), ('transferred', 'Transferred'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('emergency_escalated', 'Emergency Escalated')], max_length=30)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('intake_in_progress', 'Intake in Progress'), ('intake_completed', 'Intake Completed'), ('doctor_review', 'Doctor Review'), ('awaiting_patient_response', 'Awaiting Patient Response'), ('awaiting_doctor_response', 'Awaiting Doctor Response'), ('under_review', 'Under Review'), ('follow_up_required', 'Follow-up Required'), ('physical_visit_required', 'Physical Visit Required'), ('transferred', 'Transferred'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('emergency_escalated', 'Emergency Escalated')], max_length=30)),
                ('reason', models.TextField(blank=True, max_length=1000)),
                ('client_request_id', models.UUIDField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_consultation_actions', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_actions', to='consultations.consultation')),
                ('target_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_doctor_actions', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['consultation', 'created_at'], name='consultatio_consult_ce840e_idx'), models.Index(fields=['consultation', 'action'], name='consultatio_consult_58e280_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor', 'client_request_id'), name='doctor_action_unique_actor_request_id')],
            },
        ),
    ]
