# Generated by Django 5.1.7 on 2026-07-12 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_alter_consultation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIntakeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('awaiting_patient', 'Awaiting Patient'), ('ready_for_review', 'Ready for Review'), ('confirmed', 'Confirmed'), ('emergency_stopped', 'Emergency Stopped'), ('failed', 'Failed')], default='not_started', max_length=25, verbose_name='status')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('ku', 'Kurdish')], default='en', max_length=10, verbose_name='language')),
                ('current_question', models.TextField(blank=True, verbose_name='current question')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='question count')),
                ('emergency_detected', models.BooleanField(default=False, verbose_name='emergency detected')),
                ('emergency_level', models.CharField(choices=[('none', 'None'), ('warning', 'Warning'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='none', max_length=15, verbose_name='emergency level')),
                ('emergency_reasons', models.JSONField(blank=True, default=list, verbose_name='emergency reasons')),
                ('collected_data', models.JSONField(blank=True, default=dict, verbose_name='collected data')),
                ('missing_fields', models.JSONField(blank=True, default=list, verbose_name='missing fields')),
                ('ai_provider', models.CharField(blank=True, max_length=30, verbose_name='AI provider')),
                ('ai_model', models.CharField(blank=True, max_length=60, verbose_name='AI model')),
                ('prompt_version', models.CharField(blank=True, max_length=30, verbose_name='prompt version')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('last_ai_request_at', models.DateTimeField(blank=True, null=True, verbose_name='last AI request at')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='input tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='output tokens')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='total tokens')),
                ('error_code', models.CharField(blank=True, max_length=30, verbose_name='error code')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_session', to='consultations.consultation', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'AI intake session',
                'verbose_name_plural': 'AI intake sessions',
            },
        ),
        migrations.CreateModel(
            name='AIIntakeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', 'System'), ('assistant', 'Assistant'), ('patient', 'Patient')], max_length=10, verbose_name='role')),
                ('content', models.TextField(verbose_name='content')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='sequence number')),
                ('structured_data', models.JSONField(blank=True, null=True, verbose_name='structured data')),
                ('emergency_flags', models.JSONField(blank=True, default=list, verbose_name='emergency flags')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_intake.aiintakesession', verbose_name='session')),
            ],
            options={
                'verbose_name': 'AI intake message',
                'verbose_name_plural': 'AI intake messages',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.AddIndex(
            model_name='aiintakesession',
            index=models.Index(fields=['status'], name='ai_intake_a_status_4cc03d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiintakesession',
            index=models.Index(fields=['emergency_level'], name='ai_intake_a_emergen_b7d43d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiintakesession',
            index=models.Index(fields=['created_at'], name='ai_intake_a_created_fd8e73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aiintakemessage',
            unique_together={('session', 'sequence_number')},
        ),
    ]
