# Generated by Django 5.1.15 on 2026-08-02 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_intake', '0002_message_client_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiintakesession',
            name='error_message',
        ),
        migrations.AddField(
            model_name='aiintakesession',
            name='confirmation_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='confirmation snapshot'),
        ),
        migrations.AddField(
            model_name='aiintakesession',
            name='emergency_escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='emergency escalated at'),
        ),
        migrations.AddField(
            model_name='aiintakesession',
            name='field_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='field metadata'),
        ),
        migrations.AddField(
            model_name='aiintakesession',
            name='patient_review_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='patient review summary'),
        ),
        migrations.AddField(
            model_name='aiintakesession',
            name='provider_calls',
            field=models.PositiveIntegerField(default=0, verbose_name='provider calls'),
        ),
        migrations.AddField(
            model_name='aiintakesession',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='retry count'),
        ),
        migrations.AddField(
            model_name='aiintakesession',
            name='schema_version',
            field=models.CharField(blank=True, max_length=30, verbose_name='schema version'),
        ),
        migrations.AddField(
            model_name='aiintakesession',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submitted at'),
        ),
        migrations.AddField(
            model_name='aiintakesession',
            name='suggested_relevant_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='suggested relevant fields'),
        ),
        migrations.AlterField(
            model_name='aiintakesession',
            name='error_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='error code'),
        ),
        migrations.AlterField(
            model_name='aiintakesession',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('awaiting_patient_review', 'Awaiting Patient Review'), ('correction_in_progress', 'Correction In Progress'), ('confirmed', 'Confirmed'), ('submitted_to_doctor', 'Submitted To Doctor'), ('emergency_stopped', 'Emergency Stopped'), ('temporarily_unavailable', 'Temporarily Unavailable'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='not_started', max_length=30, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='IntakeIdempotencyLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=24)),
                ('client_request_id', models.UUIDField()),
                ('result_code', models.CharField(blank=True, max_length=40)),
                ('provider_call_count', models.PositiveIntegerField(default=0)),
                ('state_before', models.CharField(blank=True, max_length=30)),
                ('state_after', models.CharField(blank=True, max_length=30)),
                ('token_delta', models.PositiveIntegerField(default=0)),
                ('emergency_level_code', models.CharField(blank=True, max_length=15)),
                ('prompt_version', models.CharField(blank=True, max_length=30)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_ledger', to='ai_intake.aiintakesession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', '-created_at'], name='ai_intake_i_session_6f86b0_idx'), models.Index(fields=['session', 'action', 'client_request_id'], name='ai_intake_i_session_b94eaf_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'action', 'client_request_id'), name='intake_unique_session_action_request')],
            },
        ),
    ]
