# Generated by Django 5.1.7 on 2026-07-12 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_title', models.CharField(blank=True, max_length=255, verbose_name='professional title')),
                ('license_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='license number')),
                ('qualifications', models.TextField(blank=True, help_text='List of medical qualifications, one per line.', verbose_name='qualifications')),
                ('biography', models.TextField(blank=True, verbose_name='biography')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='consultation fee')),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of languages the doctor speaks, e.g. ["English", "Arabic"]', verbose_name='languages')),
                ('is_approved', models.BooleanField(default=False, help_text='Designates whether this doctor has been approved by a coordinator or admin.', verbose_name='approved')),
                ('is_accepting_consultations', models.BooleanField(default=False, help_text='Designates whether the doctor is currently accepting new consultations.', verbose_name='accepting consultations')),
                ('estimated_response_minutes', models.PositiveIntegerField(default=60, verbose_name='estimated response time (minutes)')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profiles', to='specialties.specialty', verbose_name='specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'doctor profile',
                'verbose_name_plural': 'doctor profiles',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
