# Generated by Django 5.1.7 on 2026-07-18 12:52

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctoravailability'),
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='approval_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='approval note'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=16, verbose_name='approval status'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='workplace_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='workplace name'),
        ),
        migrations.AddConstraint(
            model_name='doctorprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('license_number'), condition=models.Q(('license_number', ''), _negated=True), name='doctors_unique_license_number_ci'),
        ),
    ]
