# Generated by Django 5.1.7 on 2026-07-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_approval_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_license_document',
            field=models.FileField(blank=True, help_text='Uploaded copy of the medical license for staff verification.', max_length=500, upload_to='license_documents/', verbose_name='medical license document'),
        ),
    ]
