# Generated by Django 5.1.7 on 2026-07-20 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_add_license_document_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_provider', models.CharField(max_length=50, verbose_name='storage provider')),
                ('storage_key', models.CharField(max_length=500, unique=True, verbose_name='storage key')),
                ('original_filename', models.CharField(max_length=500, verbose_name='original filename')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='extension')),
                ('declared_mime_type', models.CharField(blank=True, max_length=100, verbose_name='declared MIME type')),
                ('detected_mime_type', models.CharField(blank=True, max_length=100, verbose_name='detected MIME type')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='size bytes')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('scan_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('clean', 'Clean'), ('suspicious', 'Suspicious'), ('infected', 'Infected'), ('failed', 'Failed')], default='not_required', max_length=20, verbose_name='scan status')),
                ('is_verified', models.BooleanField(default=False, help_text='Staff has verified the document matches the applicant.', verbose_name='verified')),
                ('doctor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_document', to='doctors.doctorprofile', verbose_name='doctor profile')),
            ],
            options={
                'verbose_name': 'license document',
                'verbose_name_plural': 'license documents',
            },
        ),
    ]
