# Generated by Django 5.1.7 on 2026-07-18 08:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0004_consultationprioritychange_consultationtransfer'),
        ('doctors', '0002_doctoravailability'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (worst) to 5 (best).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('is_anonymous', models.BooleanField(default=False, help_text="If true, the reviewer's identity is hidden.", verbose_name='anonymous')),
                ('status', models.CharField(choices=[('published', 'Published'), ('under_review', 'Under Review'), ('hidden', 'Hidden'), ('removed', 'Removed')], default='published', max_length=20, verbose_name='status')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='moderated at')),
                ('moderation_reason', models.TextField(blank=True, verbose_name='moderation reason')),
                ('edit_count', models.PositiveSmallIntegerField(default=0, verbose_name='edit count')),
                ('last_edited_at', models.DateTimeField(blank=True, null=True, verbose_name='last edited at')),
                ('has_response', models.BooleanField(default=False, verbose_name='has response')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='consultations.consultation', verbose_name='consultation')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='moderated by')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='patients.patientprofile', verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'consultation review',
                'verbose_name_plural': 'consultation reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorReviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='body')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to='doctors.doctorprofile', verbose_name='doctor')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.consultationreview', verbose_name='review')),
            ],
            options={
                'verbose_name': 'doctor review response',
                'verbose_name_plural': 'doctor review responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('fake', 'Fake Review'), ('conflict_of_interest', 'Conflict of Interest'), ('privacy_violation', 'Privacy Violation'), ('other', 'Other')], max_length=50, verbose_name='reason')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('resolution', models.CharField(blank=True, choices=[('dismissed', 'Dismissed'), ('content_hidden', 'Content Hidden'), ('content_removed', 'Content Removed'), ('reviewer_warned', 'Reviewer Warned'), ('reviewer_suspended', 'Reviewer Suspended')], max_length=30, verbose_name='resolution')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.consultationreview', verbose_name='review')),
            ],
            options={
                'verbose_name': 'review report',
                'verbose_name_plural': 'review reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='consultationreview',
            index=models.Index(fields=['status'], name='reviews_con_status_11c254_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationreview',
            index=models.Index(fields=['reviewer', 'status'], name='reviews_con_reviewe_763f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationreview',
            index=models.Index(fields=['rating'], name='reviews_con_rating_375212_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['review', 'resolved_at'], name='reviews_rev_review__fe3953_idx'),
        ),
    ]
