# Generated by Django 5.1.7 on 2026-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_phase5_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('consultation_accepted', 'Consultation Accepted'), ('consultation_cancelled', 'Consultation Cancelled'), ('intake_completed', 'Intake Completed'), ('record_confirmed', 'Record Confirmed'), ('record_revision_requested', 'Record Revision Requested'), ('status_change', 'Status Change'), ('review_available', 'Review Available'), ('review_response', 'Review Response'), ('moderation_state', 'Moderation State'), ('report_resolution', 'Report Resolution')], max_length=40, verbose_name='notification type'),
        ),
    ]
